(function () {
    let KNOB_CATEGORIES_GUITAR = [
        { name: 'PATCH', key: 0 },
        { name: 'TUNER', key: 1 },
        { name: 'MASTER', key: 2 },
        { name: 'CONTROL MODE', key: 3 },
        { name: 'INPUT SETTING', key: 4 },
        { name: 'OUTPUT SETTING', key: 5 },
        { name: 'TOTAL', key: 6 },
        { name: 'MAIN GLOBAL EQ L/S', key: 7 },
        { name: 'MAIN GLOBAL EQ R', key: 8 },
        { name: 'SUB GLOBAL EQ L/S', key: 9 },
        { name: 'SUB GLOBAL EQ R', key: 10 },
        { name: 'USB AUDIO', key: 11 },
        { name: 'GUITAR TO MIDI', key: 12 },
    ];

    let KNOB_CATEGORIES_BASS = [
        { name: 'PATCH', key: 0 },
        { name: 'TUNER', key: 1 },
        { name: 'MASTER', key: 2 },
        { name: 'CONTROL MODE', key: 3 },
        { name: 'INPUT SETTING', key: 4 },
        { name: 'OUTPUT SETTING', key: 5 },
        { name: 'TOTAL', key: 6 },
        { name: 'MAIN GLOBAL EQ L/S', key: 7 },
        { name: 'MAIN GLOBAL EQ R', key: 8 },
        { name: 'SUB GLOBAL EQ L/S', key: 9 },
        { name: 'SUB GLOBAL EQ R', key: 10 },
        { name: 'USB AUDIO', key: 11 },
        { name: 'BASS TO MIDI', key: 12 },
    ];
    
    let KNOB_PARAMETERS_GUITAR = [
        { category: 0, name: 'PATCH SELECT', offset: 0 },
        { category: 1, name: 'ON/OFF', offset: 0 },
        { category: 2, name: 'BPM', offset: 0 },
        { category: 2, name: 'KEY', offset: 0 },
        { category: 2, name: 'PATCH LEVEL', offset: 0 },
        { category: 3, name: 'CONTROL MODE', offset: 0 },
        { category: 4, name: 'GK SET', offset: 0 },
        { category: 4, name: 'NORMAL SET', offset: 0 },
        { category: 5, name: 'MAIN OUTPUT-L LEVEL', offset: 0 },
        { category: 5, name: 'MAIN OUTPUT-R LEVEL', offset: 0 },
        { category: 5, name: 'MAIN OUTPUT-L SELECT', offset: 0 },
        { category: 5, name: 'MAIN OUTPUT-R SELECT', offset: 0 },
        { category: 5, name: 'SUB OUTPUT-L LEVEL', offset: 0 },
        { category: 5, name: 'SUB OUTPUT-R LEVEL', offset: 0 },
        { category: 5, name: 'SUB OUTPUT-L SELECT', offset: 0 },
        { category: 5, name: 'SUB OUTPUT-R SELECT', offset: 0 },
        { category: 6, name: 'TOTAL REVERB LEVEL', offset: 0 },
        { category: 6, name: 'TOTAL NS THRESHOLD', offset: 0 },
        { category: 7, name: 'LOW CUT', offset: 0 },
        { category: 7, name: 'LOW GAIN', offset: 0 },
        { category: 7, name: 'LOW-MID FREQ', offset: 0 },
        { category: 7, name: 'LOW-MID Q', offset: 0 },
        { category: 7, name: 'LOW-MID GAIN', offset: 0 },
        { category: 7, name: 'HIGH-MID FREQ', offset: 0 },
        { category: 7, name: 'HIGH-MID Q', offset: 0 },
        { category: 7, name: 'HIGH-MID GAIN', offset: 0 },
        { category: 7, name: 'HIGH GAIN', offset: 0 },
        { category: 7, name: 'HIGH CUT', offset: 0 },
        { category: 8, name: 'LOW CUT', offset: 0 },
        { category: 8, name: 'LOW GAIN', offset: 0 },
        { category: 8, name: 'LOW-MID FREQ', offset: 0 },
        { category: 8, name: 'LOW-MID Q', offset: 0 },
        { category: 8, name: 'LOW-MID GAIN', offset: 0 },
        { category: 8, name: 'HIGH-MID FREQ', offset: 0 },
        { category: 8, name: 'HIGH-MID Q', offset: 0 },
        { category: 8, name: 'HIGH-MID GAIN', offset: 0 },
        { category: 8, name: 'HIGH GAIN', offset: 0 },
        { category: 8, name: 'HIGH CUT', offset: 0 },
        { category: 9, name: 'LOW CUT', offset: 0 },
        { category: 9, name: 'LOW GAIN', offset: 0 },
        { category: 9, name: 'LOW-MID FREQ', offset: 0 },
        { category: 9, name: 'LOW-MID Q', offset: 0 },
        { category: 9, name: 'LOW-MID GAIN', offset: 0 },
        { category: 9, name: 'HIGH-MID FREQ', offset: 0 },
        { category: 9, name: 'HIGH-MID Q', offset: 0 },
        { category: 9, name: 'HIGH-MID GAIN', offset: 0 },
        { category: 9, name: 'HIGH GAIN', offset: 0 },
        { category: 9, name: 'HIGH CUT', offset: 0 },
        { category: 10, name: 'LOW CUT', offset: 0 },
        { category: 10, name: 'LOW GAIN', offset: 0 },
        { category: 10, name: 'LOW-MID FREQ', offset: 0 },
        { category: 10, name: 'LOW-MID Q', offset: 0 },
        { category: 10, name: 'LOW-MID GAIN', offset: 0 },
        { category: 10, name: 'HIGH-MID FREQ', offset: 0 },
        { category: 10, name: 'HIGH-MID Q', offset: 0 },
        { category: 10, name: 'HIGH-MID GAIN', offset: 0 },
        { category: 10, name: 'HIGH GAIN', offset: 0 },
        { category: 10, name: 'HIGH CUT', offset: 0 },
        { category: 11, name: 'MAIN MIX LEVEL', offset: 0 },
        { category: 11, name: 'SUB MIX LEVEL', offset: 0 },
        { category: 11, name: 'IN LEVEL', offset: 0 },
        { category: 11, name: 'OUT LEVEL', offset: 0 },
        { category: 11, name: 'USB AUDIO ROUTING', offset: 0 },
        { category: 11, name: 'USB IN POSITION', offset: 0 },
        { category: 11, name: 'USB OUT POSITION', offset: 0 },
        { category: 12, name: 'GUITAR TO MIDI SW', offset: 0 },
    ];

    let KNOB_PARAMETERS_BASS = [
        { category: 0, name: 'PATCH SELECT', offset: 0 },
        { category: 1, name: 'ON/OFF', offset: 0 },
        { category: 2, name: 'BPM', offset: 0 },
        { category: 2, name: 'KEY', offset: 0 },
        { category: 2, name: 'PATCH LEVEL', offset: 0 },
        { category: 3, name: 'CONTROL MODE', offset: 0 },
        { category: 4, name: 'GK SET', offset: 0 },
        { category: 4, name: 'NORMAL SET', offset: 0 },
        { category: 5, name: 'MAIN OUTPUT-L LEVEL', offset: 0 },
        { category: 5, name: 'MAIN OUTPUT-R LEVEL', offset: 0 },
        { category: 5, name: 'MAIN OUTPUT-L SELECT', offset: 0 },
        { category: 5, name: 'MAIN OUTPUT-R SELECT', offset: 0 },
        { category: 5, name: 'SUB OUTPUT-L LEVEL', offset: 0 },
        { category: 5, name: 'SUB OUTPUT-R LEVEL', offset: 0 },
        { category: 5, name: 'SUB OUTPUT-L SELECT', offset: 0 },
        { category: 5, name: 'SUB OUTPUT-R SELECT', offset: 0 },
        { category: 6, name: 'TOTAL REVERB LEVEL', offset: 0 },
        { category: 6, name: 'TOTAL NS THRESHOLD', offset: 0 },
        { category: 7, name: 'LOW CUT', offset: 0 },
        { category: 7, name: 'LOW GAIN', offset: 0 },
        { category: 7, name: 'LOW-MID FREQ', offset: 0 },
        { category: 7, name: 'LOW-MID Q', offset: 0 },
        { category: 7, name: 'LOW-MID GAIN', offset: 0 },
        { category: 7, name: 'HIGH-MID FREQ', offset: 0 },
        { category: 7, name: 'HIGH-MID Q', offset: 0 },
        { category: 7, name: 'HIGH-MID GAIN', offset: 0 },
        { category: 7, name: 'HIGH GAIN', offset: 0 },
        { category: 7, name: 'HIGH CUT', offset: 0 },
        { category: 8, name: 'LOW CUT', offset: 0 },
        { category: 8, name: 'LOW GAIN', offset: 0 },
        { category: 8, name: 'LOW-MID FREQ', offset: 0 },
        { category: 8, name: 'LOW-MID Q', offset: 0 },
        { category: 8, name: 'LOW-MID GAIN', offset: 0 },
        { category: 8, name: 'HIGH-MID FREQ', offset: 0 },
        { category: 8, name: 'HIGH-MID Q', offset: 0 },
        { category: 8, name: 'HIGH-MID GAIN', offset: 0 },
        { category: 8, name: 'HIGH GAIN', offset: 0 },
        { category: 8, name: 'HIGH CUT', offset: 0 },
        { category: 9, name: 'LOW CUT', offset: 0 },
        { category: 9, name: 'LOW GAIN', offset: 0 },
        { category: 9, name: 'LOW-MID FREQ', offset: 0 },
        { category: 9, name: 'LOW-MID Q', offset: 0 },
        { category: 9, name: 'LOW-MID GAIN', offset: 0 },
        { category: 9, name: 'HIGH-MID FREQ', offset: 0 },
        { category: 9, name: 'HIGH-MID Q', offset: 0 },
        { category: 9, name: 'HIGH-MID GAIN', offset: 0 },
        { category: 9, name: 'HIGH GAIN', offset: 0 },
        { category: 9, name: 'HIGH CUT', offset: 0 },
        { category: 10, name: 'LOW CUT', offset: 0 },
        { category: 10, name: 'LOW GAIN', offset: 0 },
        { category: 10, name: 'LOW-MID FREQ', offset: 0 },
        { category: 10, name: 'LOW-MID Q', offset: 0 },
        { category: 10, name: 'LOW-MID GAIN', offset: 0 },
        { category: 10, name: 'HIGH-MID FREQ', offset: 0 },
        { category: 10, name: 'HIGH-MID Q', offset: 0 },
        { category: 10, name: 'HIGH-MID GAIN', offset: 0 },
        { category: 10, name: 'HIGH GAIN', offset: 0 },
        { category: 10, name: 'HIGH CUT', offset: 0 },
        { category: 11, name: 'MAIN MIX LEVEL', offset: 0 },
        { category: 11, name: 'SUB MIX LEVEL', offset: 0 },
        { category: 11, name: 'IN LEVEL', offset: 0 },
        { category: 11, name: 'OUT LEVEL', offset: 0 },
        { category: 11, name: 'USB AUDIO ROUTING', offset: 0 },
        { category: 11, name: 'USB IN POSITION', offset: 0 },
        { category: 11, name: 'USB OUT POSITION', offset: 0 },
        { category: 12, name: 'BASS TO MIDI SW', offset: 0 },
    ];

    window.KNOB_CATEGORIES = [];
    window.KNOB_PARAMETERS = [];

    window.settingKnobConst = function () {
        if (APP_MODE === MODE.GUITAR) {
            KNOB_CATEGORIES = KNOB_CATEGORIES_GUITAR;
            KNOB_PARAMETERS = KNOB_PARAMETERS_GUITAR;
        } else {
            KNOB_CATEGORIES = KNOB_CATEGORIES_BASS;
            KNOB_PARAMETERS = KNOB_PARAMETERS_BASS;
        }

        KNOB_PARAMETERS.forEach(function (PARAMETER, i) {
            let category = PARAMETER.category;
            if (category < 0) {
                return;
            }
            if (KNOB_CATEGORIES[category].from === undefined) {
                KNOB_CATEGORIES[category].from = i;
            }
            KNOB_CATEGORIES[category].to = (i + 1);
        });
    }
})();
