//
//	librarian_setting.js
//
//	Copyright 2016 Roland Corporation. All rights reserved.
//

// ----------------------------------------
// for GUITAR MODE
// ----------------------------------------
function LibrarianSetting() {

	this.rows = 200; //ProductSetting.numOfUserPatch

	this.blockSet = [ // see EditorSetting1 and EditorSetting2 of editor_setting.js
		'User_patch%common',
		// 'User_patch%common2',
		'User_patch%led',
		'User_patch%assign(1)',
		'User_patch%assign(2)',
		'User_patch%assign(3)',
		'User_patch%assign(4)',
		'User_patch%assign(5)',
		'User_patch%assign(6)',
		'User_patch%assign(7)',
		'User_patch%assign(8)',
		'User_patch%assign(9)',
		'User_patch%assign(10)',
		'User_patch%assign(11)',
		'User_patch%assign(12)',
		'User_patch%assign(13)',
		'User_patch%assign(14)',
		'User_patch%assign(15)',
		'User_patch%assign(16)',
//		'User_patch%padding',

		'User_patch%efct',
		'User_patch%gtr2midi',

		'User_patch%inst(1)%inst',
		'User_patch%inst(1)%instDynaSynth',
		'User_patch%inst(1)%instOscSynth',
		'User_patch%inst(1)%instGr300',
		'User_patch%inst(1)%instEGtr',
		'User_patch%inst(1)%instAcoustic',
		'User_patch%inst(1)%instEBass',
		'User_patch%inst(1)%instVioGtr',
		'User_patch%inst(1)%instPolyFx',
		'User_patch%inst(1)%instAltTune',

		'User_patch%inst(2)%inst',
		'User_patch%inst(2)%instDynaSynth',
		'User_patch%inst(2)%instOscSynth',
		'User_patch%inst(2)%instGr300',
		'User_patch%inst(2)%instEGtr',
		'User_patch%inst(2)%instAcoustic',
		'User_patch%inst(2)%instEBass',
		'User_patch%inst(2)%instVioGtr',
		'User_patch%inst(2)%instPolyFx',
		'User_patch%inst(2)%instAltTune',

		'User_patch%inst(3)%inst',
		'User_patch%inst(3)%instDynaSynth',
		'User_patch%inst(3)%instOscSynth',
		'User_patch%inst(3)%instGr300',
		'User_patch%inst(3)%instEGtr',
		'User_patch%inst(3)%instAcoustic',
		'User_patch%inst(3)%instEBass',
		'User_patch%inst(3)%instVioGtr',
		'User_patch%inst(3)%instPolyFx',
		'User_patch%inst(3)%instAltTune',

		'User_patch%comp',
		'User_patch%dist',
		'User_patch%amp',
		'User_patch%ns',
		'User_patch%eq(1)',
		'User_patch%eq(2)',
		'User_patch%delay(1)',
		'User_patch%delay(2)',
		'User_patch%mstDelay',
		'User_patch%chorus',

		'User_patch%fx(1)%fx',
		'User_patch%fx(1)%fxAcReso',
		'User_patch%fx(1)%fxAWah',
		'User_patch%fx(1)%fxChorus',
		'User_patch%fx(1)%fxCVibe',
		'User_patch%fx(1)%fxComp',
		'User_patch%fx(1)%fxDefretter',
		'User_patch%fx(1)%fxDefretterBass',
		'User_patch%fx(1)%fxDelay',
		'User_patch%fx(1)%fxFlanger',
		'User_patch%fx(1)%fxFlangerBass',
		'User_patch%fx(1)%fxFv',
		'User_patch%fx(1)%fxGEq',
		'User_patch%fx(1)%fxHarmonist',
		'User_patch%fx(1)%fxHumanizer',
		'User_patch%fx(1)%fxIsolator',
		'User_patch%fx(1)%fxLimiter',
		'User_patch%fx(1)%fxLofi',
		'User_patch%fx(1)%fxOctave',
		'User_patch%fx(1)%fxOctaveBass',
		'User_patch%fx(1)%fxPan',
		'User_patch%fx(1)%fxPEq',
		'User_patch%fx(1)%fxPedalBend',
		'User_patch%fx(1)%fxPhaser',
		'User_patch%fx(1)%fxPitchShift',
		'User_patch%fx(1)%fxReverb',
		'User_patch%fx(1)%fxRingMod',
		'User_patch%fx(1)%fxRotary',
		'User_patch%fx(1)%fxSitarSim',
		'User_patch%fx(1)%fxSlicer',
		'User_patch%fx(1)%fxSlowGear',
		'User_patch%fx(1)%fxSlowGearBass',
		'User_patch%fx(1)%fxSoundHold',
		'User_patch%fx(1)%fxTWah',
		'User_patch%fx(1)%fxTWahBass',
		'User_patch%fx(1)%fxTremolo',
		'User_patch%fx(1)%fxVibrato',
		'User_patch%fx(1)%fxWah',
		
		'User_patch%fx(2)%fx',
		'User_patch%fx(2)%fxAcReso',
		'User_patch%fx(2)%fxAWah',
		'User_patch%fx(2)%fxChorus',
		'User_patch%fx(2)%fxCVibe',
		'User_patch%fx(2)%fxComp',
		'User_patch%fx(2)%fxDefretter',
		'User_patch%fx(2)%fxDefretterBass',
		'User_patch%fx(2)%fxDelay',
		'User_patch%fx(2)%fxFlanger',
		'User_patch%fx(2)%fxFlangerBass',
		'User_patch%fx(2)%fxFv',
		'User_patch%fx(2)%fxGEq',
		'User_patch%fx(2)%fxHarmonist',
		'User_patch%fx(2)%fxHumanizer',
		'User_patch%fx(2)%fxIsolator',
		'User_patch%fx(2)%fxLimiter',
		'User_patch%fx(2)%fxLofi',
		'User_patch%fx(2)%fxOctave',
		'User_patch%fx(2)%fxOctaveBass',
		'User_patch%fx(2)%fxPan',
		'User_patch%fx(2)%fxPEq',
		'User_patch%fx(2)%fxPedalBend',
		'User_patch%fx(2)%fxPhaser',
		'User_patch%fx(2)%fxPitchShift',
		'User_patch%fx(2)%fxReverb',
		'User_patch%fx(2)%fxRingMod',
		'User_patch%fx(2)%fxRotary',
		'User_patch%fx(2)%fxSitarSim',
		'User_patch%fx(2)%fxSlicer',
		'User_patch%fx(2)%fxSlowGear',
		'User_patch%fx(2)%fxSlowGearBass',
		'User_patch%fx(2)%fxSoundHold',
		'User_patch%fx(2)%fxTWah',
		'User_patch%fx(2)%fxTWahBass',
		'User_patch%fx(2)%fxTremolo',
		'User_patch%fx(2)%fxVibrato',
		'User_patch%fx(2)%fxWah',
		
		'User_patch%fx(3)%fx',
		'User_patch%fx(3)%fxAcReso',
		'User_patch%fx(3)%fxAWah',
		'User_patch%fx(3)%fxChorus',
		'User_patch%fx(3)%fxCVibe',
		'User_patch%fx(3)%fxComp',
		'User_patch%fx(3)%fxDefretter',
		'User_patch%fx(3)%fxDefretterBass',
		'User_patch%fx(3)%fxDelay',
		'User_patch%fx(3)%fxFlanger',
		'User_patch%fx(3)%fxFlangerBass',
		'User_patch%fx(3)%fxFv',
		'User_patch%fx(3)%fxGEq',
		'User_patch%fx(3)%fxHarmonist',
		'User_patch%fx(3)%fxHumanizer',
		'User_patch%fx(3)%fxIsolator',
		'User_patch%fx(3)%fxLimiter',
		'User_patch%fx(3)%fxLofi',
		'User_patch%fx(3)%fxOctave',
		'User_patch%fx(3)%fxOctaveBass',
		'User_patch%fx(3)%fxPan',
		'User_patch%fx(3)%fxPEq',
		'User_patch%fx(3)%fxPedalBend',
		'User_patch%fx(3)%fxPhaser',
		'User_patch%fx(3)%fxPitchShift',
		'User_patch%fx(3)%fxReverb',
		'User_patch%fx(3)%fxRingMod',
		'User_patch%fx(3)%fxRotary',
		'User_patch%fx(3)%fxSitarSim',
		'User_patch%fx(3)%fxSlicer',
		'User_patch%fx(3)%fxSlowGear',
		'User_patch%fx(3)%fxSlowGearBass',
		'User_patch%fx(3)%fxSoundHold',
		'User_patch%fx(3)%fxTWah',
		'User_patch%fx(3)%fxTWahBass',
		'User_patch%fx(3)%fxTremolo',
		'User_patch%fx(3)%fxVibrato',
		'User_patch%fx(3)%fxWah',
		
		'User_patch%reverb',
	];
	this.temporarySet = {
		'User_patch%common'                 : 'Temp_patch%common'                 ,
		// 'User_patch%common(2)'              : 'Temp_patch%common2'              ,
		'User_patch%led'                    : 'Temp_patch%led'                    ,
		'User_patch%assign(1)'              : 'Temp_patch%assign(1)'              ,
		'User_patch%assign(2)'              : 'Temp_patch%assign(2)'              ,
		'User_patch%assign(3)'              : 'Temp_patch%assign(3)'              ,
		'User_patch%assign(4)'              : 'Temp_patch%assign(4)'              ,
		'User_patch%assign(5)'              : 'Temp_patch%assign(5)'              ,
		'User_patch%assign(6)'              : 'Temp_patch%assign(6)'              ,
		'User_patch%assign(7)'              : 'Temp_patch%assign(7)'              ,
		'User_patch%assign(8)'              : 'Temp_patch%assign(8)'              ,
		'User_patch%assign(9)'              : 'Temp_patch%assign(9)'              ,
		'User_patch%assign(10)'             : 'Temp_patch%assign(10)'             ,
		'User_patch%assign(11)'             : 'Temp_patch%assign(11)'             ,
		'User_patch%assign(12)'             : 'Temp_patch%assign(12)'             ,
		'User_patch%assign(13)'             : 'Temp_patch%assign(13)'             ,
		'User_patch%assign(14)'             : 'Temp_patch%assign(14)'             ,
		'User_patch%assign(15)'             : 'Temp_patch%assign(15)'             ,
		'User_patch%assign(16)'             : 'Temp_patch%assign(16)'             ,
//		'User_patch%padding'                : 'Temp_patch%padding'                ,

		'User_patch%efct'                   : 'Temp_patch%efct'                   ,
		'User_patch%gtr2midi'               : 'Temp_patch%gtr2midi'               ,

		'User_patch%inst(1)%inst'           : 'Temp_patch%inst(1)%inst'           ,
		'User_patch%inst(1)%instDynaSynth'  : 'Temp_patch%inst(1)%instDynaSynth'  ,
		'User_patch%inst(1)%instOscSynth'   : 'Temp_patch%inst(1)%instOscSynth'   ,
		'User_patch%inst(1)%instGr300'      : 'Temp_patch%inst(1)%instGr300'      ,
		'User_patch%inst(1)%instEGtr'       : 'Temp_patch%inst(1)%instEGtr'       ,
		'User_patch%inst(1)%instAcoustic'   : 'Temp_patch%inst(1)%instAcoustic'   ,
		'User_patch%inst(1)%instEBass'      : 'Temp_patch%inst(1)%instEBass'      ,
		'User_patch%inst(1)%instVioGtr'     : 'Temp_patch%inst(1)%instVioGtr'     ,
		'User_patch%inst(1)%instPolyFx'     : 'Temp_patch%inst(1)%instPolyFx'     ,
		'User_patch%inst(1)%instAltTune'    : 'Temp_patch%inst(1)%instAltTune'    ,

		'User_patch%inst(2)%inst'           : 'Temp_patch%inst(2)%inst'           ,
		'User_patch%inst(2)%instDynaSynth'  : 'Temp_patch%inst(2)%instDynaSynth'  ,
		'User_patch%inst(2)%instOscSynth'   : 'Temp_patch%inst(2)%instOscSynth'   ,
		'User_patch%inst(2)%instGr300'      : 'Temp_patch%inst(2)%instGr300'      ,
		'User_patch%inst(2)%instEGtr'       : 'Temp_patch%inst(2)%instEGtr'       ,
		'User_patch%inst(2)%instAcoustic'   : 'Temp_patch%inst(2)%instAcoustic'   ,
		'User_patch%inst(2)%instEBass'      : 'Temp_patch%inst(2)%instEBass'      ,
		'User_patch%inst(2)%instVioGtr'     : 'Temp_patch%inst(2)%instVioGtr'     ,
		'User_patch%inst(2)%instPolyFx'     : 'Temp_patch%inst(2)%instPolyFx'     ,
		'User_patch%inst(2)%instAltTune'    : 'Temp_patch%inst(2)%instAltTune'    ,

		'User_patch%inst(3)%inst'           : 'Temp_patch%inst(3)%inst'           ,
		'User_patch%inst(3)%instDynaSynth'  : 'Temp_patch%inst(3)%instDynaSynth'  ,
		'User_patch%inst(3)%instOscSynth'   : 'Temp_patch%inst(3)%instOscSynth'   ,
		'User_patch%inst(3)%instGr300'      : 'Temp_patch%inst(3)%instGr300'      ,
		'User_patch%inst(3)%instEGtr'       : 'Temp_patch%inst(3)%instEGtr'       ,
		'User_patch%inst(3)%instAcoustic'   : 'Temp_patch%inst(3)%instAcoustic'   ,
		'User_patch%inst(3)%instEBass'      : 'Temp_patch%inst(3)%instEBass'      ,
		'User_patch%inst(3)%instVioGtr'     : 'Temp_patch%inst(3)%instVioGtr'     ,
		'User_patch%inst(3)%instPolyFx'     : 'Temp_patch%inst(3)%instPolyFx'     ,
		'User_patch%inst(3)%instAltTune'    : 'Temp_patch%inst(3)%instAltTune'    ,

		'User_patch%comp'                   : 'Temp_patch%comp'                   ,
		'User_patch%dist'                   : 'Temp_patch%dist'                   ,
		'User_patch%amp'                    : 'Temp_patch%amp'                    ,
		'User_patch%ns'                     : 'Temp_patch%ns'                     ,
		'User_patch%eq(1)'                  : 'Temp_patch%eq(1)'                  ,
		'User_patch%eq(2)'                  : 'Temp_patch%eq(2)'                  ,
		'User_patch%delay(1)'               : 'Temp_patch%delay(1)'               ,
		'User_patch%delay(2)'               : 'Temp_patch%delay(2)'               ,
		'User_patch%mstDelay'               : 'Temp_patch%mstDelay'               ,
		'User_patch%chorus'                 : 'Temp_patch%chorus'                 ,

		'User_patch%fx(1)%fx'               : 'Temp_patch%fx(1)%fx'               ,
		'User_patch%fx(1)%fxAcReso'         : 'Temp_patch%fx(1)%fxAcReso'         ,
		'User_patch%fx(1)%fxAWah'           : 'Temp_patch%fx(1)%fxAWah'           ,
		'User_patch%fx(1)%fxChorus'         : 'Temp_patch%fx(1)%fxChorus'         ,
		'User_patch%fx(1)%fxCVibe'          : 'Temp_patch%fx(1)%fxCVibe'          ,
		'User_patch%fx(1)%fxComp'           : 'Temp_patch%fx(1)%fxComp'           ,
		'User_patch%fx(1)%fxDefretter'      : 'Temp_patch%fx(1)%fxDefretter'      ,
		'User_patch%fx(1)%fxDefretterBass'  : 'Temp_patch%fx(1)%fxDefretterBass'  ,
		'User_patch%fx(1)%fxDelay'          : 'Temp_patch%fx(1)%fxDelay'          ,
		'User_patch%fx(1)%fxFlanger'        : 'Temp_patch%fx(1)%fxFlanger'        ,
		'User_patch%fx(1)%fxFlangerBass'    : 'Temp_patch%fx(1)%fxFlangerBass'    ,
		'User_patch%fx(1)%fxFv'             : 'Temp_patch%fx(1)%fxFv'             ,
		'User_patch%fx(1)%fxGEq'            : 'Temp_patch%fx(1)%fxGEq'            ,
		'User_patch%fx(1)%fxHarmonist'      : 'Temp_patch%fx(1)%fxHarmonist'      ,
		'User_patch%fx(1)%fxHumanizer'      : 'Temp_patch%fx(1)%fxHumanizer'      ,
		'User_patch%fx(1)%fxIsolator'       : 'Temp_patch%fx(1)%fxIsolator'       ,
		'User_patch%fx(1)%fxLimiter'        : 'Temp_patch%fx(1)%fxLimiter'        ,
		'User_patch%fx(1)%fxLofi'           : 'Temp_patch%fx(1)%fxLofi'           ,
		'User_patch%fx(1)%fxOctave'         : 'Temp_patch%fx(1)%fxOctave'         ,
		'User_patch%fx(1)%fxOctaveBass'     : 'Temp_patch%fx(1)%fxOctaveBass'     ,
		'User_patch%fx(1)%fxPan'            : 'Temp_patch%fx(1)%fxPan'            ,
		'User_patch%fx(1)%fxPEq'            : 'Temp_patch%fx(1)%fxPEq'            ,
		'User_patch%fx(1)%fxPedalBend'      : 'Temp_patch%fx(1)%fxPedalBend'      ,
		'User_patch%fx(1)%fxPhaser'         : 'Temp_patch%fx(1)%fxPhaser'         ,
		'User_patch%fx(1)%fxPitchShift'     : 'Temp_patch%fx(1)%fxPitchShift'     ,
		'User_patch%fx(1)%fxReverb'         : 'Temp_patch%fx(1)%fxReverb'         ,
		'User_patch%fx(1)%fxRingMod'        : 'Temp_patch%fx(1)%fxRingMod'        ,
		'User_patch%fx(1)%fxRotary'         : 'Temp_patch%fx(1)%fxRotary'         ,
		'User_patch%fx(1)%fxSitarSim'       : 'Temp_patch%fx(1)%fxSitarSim'       ,
		'User_patch%fx(1)%fxSlicer'         : 'Temp_patch%fx(1)%fxSlicer'         ,
		'User_patch%fx(1)%fxSlowGear'       : 'Temp_patch%fx(1)%fxSlowGear'       ,
		'User_patch%fx(1)%fxSlowGearBass'   : 'Temp_patch%fx(1)%fxSlowGearBass'   ,
		'User_patch%fx(1)%fxSoundHold'      : 'Temp_patch%fx(1)%fxSoundHold'      ,
		'User_patch%fx(1)%fxTWah'           : 'Temp_patch%fx(1)%fxTWah'           ,
		'User_patch%fx(1)%fxTWahBass'       : 'Temp_patch%fx(1)%fxTWahBass'       ,
		'User_patch%fx(1)%fxTremolo'        : 'Temp_patch%fx(1)%fxTremolo'        ,
		'User_patch%fx(1)%fxVibrato'        : 'Temp_patch%fx(1)%fxVibrato'        ,
		'User_patch%fx(1)%fxWah'            : 'Temp_patch%fx(1)%fxWah'            ,
		
		'User_patch%fx(2)%fx'               : 'Temp_patch%fx(2)%fx'               ,
		'User_patch%fx(2)%fxAcReso'         : 'Temp_patch%fx(2)%fxAcReso'         ,
		'User_patch%fx(2)%fxAWah'           : 'Temp_patch%fx(2)%fxAWah'           ,
		'User_patch%fx(2)%fxChorus'         : 'Temp_patch%fx(2)%fxChorus'         ,
		'User_patch%fx(2)%fxCVibe'          : 'Temp_patch%fx(2)%fxCVibe'          ,
		'User_patch%fx(2)%fxComp'           : 'Temp_patch%fx(2)%fxComp'           ,
		'User_patch%fx(2)%fxDefretter'      : 'Temp_patch%fx(2)%fxDefretter'      ,
		'User_patch%fx(2)%fxDefretterBass'  : 'Temp_patch%fx(2)%fxDefretterBass'  ,
		'User_patch%fx(2)%fxDelay'          : 'Temp_patch%fx(2)%fxDelay'          ,
		'User_patch%fx(2)%fxFlanger'        : 'Temp_patch%fx(2)%fxFlanger'        ,
		'User_patch%fx(2)%fxFlangerBass'    : 'Temp_patch%fx(2)%fxFlangerBass'    ,
		'User_patch%fx(2)%fxFv'             : 'Temp_patch%fx(2)%fxFv'             ,
		'User_patch%fx(2)%fxGEq'            : 'Temp_patch%fx(2)%fxGEq'            ,
		'User_patch%fx(2)%fxHarmonist'      : 'Temp_patch%fx(2)%fxHarmonist'      ,
		'User_patch%fx(2)%fxHumanizer'      : 'Temp_patch%fx(2)%fxHumanizer'      ,
		'User_patch%fx(2)%fxIsolator'       : 'Temp_patch%fx(2)%fxIsolator'       ,
		'User_patch%fx(2)%fxLimiter'        : 'Temp_patch%fx(2)%fxLimiter'        ,
		'User_patch%fx(2)%fxLofi'           : 'Temp_patch%fx(2)%fxLofi'           ,
		'User_patch%fx(2)%fxOctave'         : 'Temp_patch%fx(2)%fxOctave'         ,
		'User_patch%fx(2)%fxOctaveBass'     : 'Temp_patch%fx(2)%fxOctaveBass'     ,
		'User_patch%fx(2)%fxPan'            : 'Temp_patch%fx(2)%fxPan'            ,
		'User_patch%fx(2)%fxPEq'            : 'Temp_patch%fx(2)%fxPEq'            ,
		'User_patch%fx(2)%fxPedalBend'      : 'Temp_patch%fx(2)%fxPedalBend'      ,
		'User_patch%fx(2)%fxPhaser'         : 'Temp_patch%fx(2)%fxPhaser'         ,
		'User_patch%fx(2)%fxPitchShift'     : 'Temp_patch%fx(2)%fxPitchShift'     ,
		'User_patch%fx(2)%fxReverb'         : 'Temp_patch%fx(2)%fxReverb'         ,
		'User_patch%fx(2)%fxRingMod'        : 'Temp_patch%fx(2)%fxRingMod'        ,
		'User_patch%fx(2)%fxRotary'         : 'Temp_patch%fx(2)%fxRotary'         ,
		'User_patch%fx(2)%fxSitarSim'       : 'Temp_patch%fx(2)%fxSitarSim'       ,
		'User_patch%fx(2)%fxSlicer'         : 'Temp_patch%fx(2)%fxSlicer'         ,
		'User_patch%fx(2)%fxSlowGear'       : 'Temp_patch%fx(2)%fxSlowGear'       ,
		'User_patch%fx(2)%fxSlowGearBass'   : 'Temp_patch%fx(2)%fxSlowGearBass'   ,
		'User_patch%fx(2)%fxSoundHold'      : 'Temp_patch%fx(2)%fxSoundHold'      ,
		'User_patch%fx(2)%fxTWah'           : 'Temp_patch%fx(2)%fxTWah'           ,
		'User_patch%fx(2)%fxTWahBass'       : 'Temp_patch%fx(2)%fxTWahBass'       ,
		'User_patch%fx(2)%fxTremolo'        : 'Temp_patch%fx(2)%fxTremolo'        ,
		'User_patch%fx(2)%fxVibrato'        : 'Temp_patch%fx(2)%fxVibrato'        ,
		'User_patch%fx(2)%fxWah'            : 'Temp_patch%fx(2)%fxWah'            ,
		
		'User_patch%fx(3)%fx'               : 'Temp_patch%fx(3)%fx'               ,
		'User_patch%fx(3)%fxAcReso'         : 'Temp_patch%fx(3)%fxAcReso'         ,
		'User_patch%fx(3)%fxAWah'           : 'Temp_patch%fx(3)%fxAWah'           ,
		'User_patch%fx(3)%fxChorus'         : 'Temp_patch%fx(3)%fxChorus'         ,
		'User_patch%fx(3)%fxCVibe'          : 'Temp_patch%fx(3)%fxCVibe'          ,
		'User_patch%fx(3)%fxComp'           : 'Temp_patch%fx(3)%fxComp'           ,
		'User_patch%fx(3)%fxDefretter'      : 'Temp_patch%fx(3)%fxDefretter'      ,
		'User_patch%fx(3)%fxDefretterBass'  : 'Temp_patch%fx(3)%fxDefretterBass'  ,
		'User_patch%fx(3)%fxDelay'          : 'Temp_patch%fx(3)%fxDelay'          ,
		'User_patch%fx(3)%fxFlanger'        : 'Temp_patch%fx(3)%fxFlanger'        ,
		'User_patch%fx(3)%fxFlangerBass'    : 'Temp_patch%fx(3)%fxFlangerBass'    ,
		'User_patch%fx(3)%fxFv'             : 'Temp_patch%fx(3)%fxFv'             ,
		'User_patch%fx(3)%fxGEq'            : 'Temp_patch%fx(3)%fxGEq'            ,
		'User_patch%fx(3)%fxHarmonist'      : 'Temp_patch%fx(3)%fxHarmonist'      ,
		'User_patch%fx(3)%fxHumanizer'      : 'Temp_patch%fx(3)%fxHumanizer'      ,
		'User_patch%fx(3)%fxIsolator'       : 'Temp_patch%fx(3)%fxIsolator'       ,
		'User_patch%fx(3)%fxLimiter'        : 'Temp_patch%fx(3)%fxLimiter'        ,
		'User_patch%fx(3)%fxLofi'           : 'Temp_patch%fx(3)%fxLofi'           ,
		'User_patch%fx(3)%fxOctave'         : 'Temp_patch%fx(3)%fxOctave'         ,
		'User_patch%fx(3)%fxOctaveBass'     : 'Temp_patch%fx(3)%fxOctaveBass'     ,
		'User_patch%fx(3)%fxPan'            : 'Temp_patch%fx(3)%fxPan'            ,
		'User_patch%fx(3)%fxPEq'            : 'Temp_patch%fx(3)%fxPEq'            ,
		'User_patch%fx(3)%fxPedalBend'      : 'Temp_patch%fx(3)%fxPedalBend'      ,
		'User_patch%fx(3)%fxPhaser'         : 'Temp_patch%fx(3)%fxPhaser'         ,
		'User_patch%fx(3)%fxPitchShift'     : 'Temp_patch%fx(3)%fxPitchShift'     ,
		'User_patch%fx(3)%fxReverb'         : 'Temp_patch%fx(3)%fxReverb'         ,
		'User_patch%fx(3)%fxRingMod'        : 'Temp_patch%fx(3)%fxRingMod'        ,
		'User_patch%fx(3)%fxRotary'         : 'Temp_patch%fx(3)%fxRotary'         ,
		'User_patch%fx(3)%fxSitarSim'       : 'Temp_patch%fx(3)%fxSitarSim'       ,
		'User_patch%fx(3)%fxSlicer'         : 'Temp_patch%fx(3)%fxSlicer'         ,
		'User_patch%fx(3)%fxSlowGear'       : 'Temp_patch%fx(3)%fxSlowGear'       ,
		'User_patch%fx(3)%fxSlowGearBass'   : 'Temp_patch%fx(3)%fxSlowGearBass'   ,
		'User_patch%fx(3)%fxSoundHold'      : 'Temp_patch%fx(3)%fxSoundHold'      ,
		'User_patch%fx(3)%fxTWah'           : 'Temp_patch%fx(3)%fxTWah'           ,
		'User_patch%fx(3)%fxTWahBass'       : 'Temp_patch%fx(3)%fxTWahBass'       ,
		'User_patch%fx(3)%fxTremolo'        : 'Temp_patch%fx(3)%fxTremolo'        ,
		'User_patch%fx(3)%fxVibrato'        : 'Temp_patch%fx(3)%fxVibrato'        ,
		'User_patch%fx(3)%fxWah'            : 'Temp_patch%fx(3)%fxWah'            ,
		
		'User_patch%reverb'                 : 'Temp_patch%reverb'                 ,
	};

	this.columnInfo = [
		{ type: 'text16', width: '16' },
	];
	this.value = function (paramSet, column) {
		var text = '';
		var data = paramSet['User_patch%common']; // TODO_20191217 : come to here even if BASS MDOE
		for (var i = 0; i < 16; i++) {
			text += String.fromCharCode(parseInt(data[i], 16));
		}
		return text;
	}
	this.setValue = function (paramSet, column, value) {
		var data = paramSet['User_patch%common'];
		for (var i = 0; i < 16; i++) {
			var code = (i < value.length) ? value.charCodeAt(i) : 32;
			if (code < 32 || code > 127) code = 32;
			data[i] = code.toString(16);
		}
	}

	this.readStart = function (midi) { }
	this.readStop = function (midi) { }
	this.writeStart = function (midi) { }
	this.writeCommand = function (midi) { }
	this.writeStop = function (midi) { }
	this.writeTemporaryStart = function (midi, row) { }
	this.writeTemporaryStop = function (midi) { }
	this.previewStart = function (midi) { }
	this.previewStop = function (midi) { }
	this.getPatchVariationSet = function() { return this.exclusionSet; }
}


// ----------------------------------------
// for BASS MODE
// ----------------------------------------
function LibrarianSettingBass() {

	this.rows = 200; //ProductSetting.numOfUserPatch

	this.blockSet = [ // see EditorSettingBass1 and EditorSettingBass2 of editor_setting.js
		'UserBass_patch%common',
		// 'UserBass_patch%common(2)',
		'UserBass_patch%led',
		'UserBass_patch%assign(1)',
		'UserBass_patch%assign(2)',
		'UserBass_patch%assign(3)',
		'UserBass_patch%assign(4)',
		'UserBass_patch%assign(5)',
		'UserBass_patch%assign(6)',
		'UserBass_patch%assign(7)',
		'UserBass_patch%assign(8)',
		'UserBass_patch%assign(9)',
		'UserBass_patch%assign(10)',
		'UserBass_patch%assign(11)',
		'UserBass_patch%assign(12)',
		'UserBass_patch%assign(13)',
		'UserBass_patch%assign(14)',
		'UserBass_patch%assign(15)',
		'UserBass_patch%assign(16)',
//		'UserBass_patch%padding',

		'UserBass_patch%efct',
		'UserBass_patch%gtr2midi',

		'UserBass_patch%inst(1)%inst',
		'UserBass_patch%inst(1)%instDynaSynth',
		'UserBass_patch%inst(1)%instOscSynth',
		'UserBass_patch%inst(1)%instAnalogGr',
		'UserBass_patch%inst(1)%instEBass',
		'UserBass_patch%inst(1)%instAcBass',
		'UserBass_patch%inst(1)%instEGtr',
		// 'UserBass_patch%inst(1)%instAcoustic',
		// 'UserBass_patch%inst(1)%instVioGtr',
		'UserBass_patch%inst(1)%instPolyFx',
		'UserBass_patch%inst(1)%instAltTune',

		'UserBass_patch%inst(2)%inst',
		'UserBass_patch%inst(2)%instDynaSynth',
		'UserBass_patch%inst(2)%instOscSynth',
		'UserBass_patch%inst(2)%instAnalogGr',
		'UserBass_patch%inst(2)%instEBass',
		'UserBass_patch%inst(2)%instAcBass',
		'UserBass_patch%inst(2)%instEGtr',
		// 'UserBass_patch%inst(2)%instAcoustic',
		// 'UserBass_patch%inst(2)%instVioGtr',
		'UserBass_patch%inst(2)%instPolyFx',
		'UserBass_patch%inst(2)%instAltTune',

		'UserBass_patch%inst(3)%inst',
		'UserBass_patch%inst(3)%instDynaSynth',
		'UserBass_patch%inst(3)%instOscSynth',
		'UserBass_patch%inst(3)%instAnalogGr',
		'UserBass_patch%inst(3)%instEBass',
		'UserBass_patch%inst(3)%instAcBass',
		'UserBass_patch%inst(3)%instEGtr',
		// 'UserBass_patch%inst(3)%instAcoustic',
		// 'UserBass_patch%inst(3)%instVioGtr',
		'UserBass_patch%inst(3)%instPolyFx',
		'UserBass_patch%inst(3)%instAltTune',

		'UserBass_patch%comp',
		'UserBass_patch%dist',
		'UserBass_patch%amp',
		'UserBass_patch%ns',
		'UserBass_patch%eq(1)',
		'UserBass_patch%eq(2)',
		'UserBass_patch%delay(1)',
		'UserBass_patch%delay(2)',
		'UserBass_patch%mstDelay',
		'UserBass_patch%chorus',

		'UserBass_patch%fx(1)%fx',
		'UserBass_patch%fx(1)%fxAcReso',
		'UserBass_patch%fx(1)%fxAWah',
		'UserBass_patch%fx(1)%fxChorus',
		'UserBass_patch%fx(1)%fxCVibe',
		'UserBass_patch%fx(1)%fxComp',
		'UserBass_patch%fx(1)%fxDefretter',
		'UserBass_patch%fx(1)%fxDefretterBass',
		'UserBass_patch%fx(1)%fxDelay',
		'UserBass_patch%fx(1)%fxFlanger',
		'UserBass_patch%fx(1)%fxFlangerBass',
		'UserBass_patch%fx(1)%fxFv',
		'UserBass_patch%fx(1)%fxGEq',
		'UserBass_patch%fx(1)%fxHarmonist',
		'UserBass_patch%fx(1)%fxHumanizer',
		'UserBass_patch%fx(1)%fxIsolator',
		'UserBass_patch%fx(1)%fxLimiter',
		'UserBass_patch%fx(1)%fxLofi',
		'UserBass_patch%fx(1)%fxOctave',
		'UserBass_patch%fx(1)%fxOctaveBass',
		'UserBass_patch%fx(1)%fxPan',
		'UserBass_patch%fx(1)%fxPEq',
		'UserBass_patch%fx(1)%fxPedalBend',
		'UserBass_patch%fx(1)%fxPhaser',
		'UserBass_patch%fx(1)%fxPitchShift',
		'UserBass_patch%fx(1)%fxReverb',
		'UserBass_patch%fx(1)%fxRingMod',
		'UserBass_patch%fx(1)%fxRotary',
		'UserBass_patch%fx(1)%fxSitarSim',
		'UserBass_patch%fx(1)%fxSlicer',
		'UserBass_patch%fx(1)%fxSlowGear',
		'UserBass_patch%fx(1)%fxSlowGearBass',
		'UserBass_patch%fx(1)%fxSoundHold',
		'UserBass_patch%fx(1)%fxTWah',
		'UserBass_patch%fx(1)%fxTWahBass',
		'UserBass_patch%fx(1)%fxTremolo',
		'UserBass_patch%fx(1)%fxVibrato',
		'UserBass_patch%fx(1)%fxWah',
		
		'UserBass_patch%fx(2)%fx',
		'UserBass_patch%fx(2)%fxAcReso',
		'UserBass_patch%fx(2)%fxAWah',
		'UserBass_patch%fx(2)%fxChorus',
		'UserBass_patch%fx(2)%fxCVibe',
		'UserBass_patch%fx(2)%fxComp',
		'UserBass_patch%fx(2)%fxDefretter',
		'UserBass_patch%fx(2)%fxDefretterBass',
		'UserBass_patch%fx(2)%fxDelay',
		'UserBass_patch%fx(2)%fxFlanger',
		'UserBass_patch%fx(2)%fxFlangerBass',
		'UserBass_patch%fx(2)%fxFv',
		'UserBass_patch%fx(2)%fxGEq',
		'UserBass_patch%fx(2)%fxHarmonist',
		'UserBass_patch%fx(2)%fxHumanizer',
		'UserBass_patch%fx(2)%fxIsolator',
		'UserBass_patch%fx(2)%fxLimiter',
		'UserBass_patch%fx(2)%fxLofi',
		'UserBass_patch%fx(2)%fxOctave',
		'UserBass_patch%fx(2)%fxOctaveBass',
		'UserBass_patch%fx(2)%fxPan',
		'UserBass_patch%fx(2)%fxPEq',
		'UserBass_patch%fx(2)%fxPedalBend',
		'UserBass_patch%fx(2)%fxPhaser',
		'UserBass_patch%fx(2)%fxPitchShift',
		'UserBass_patch%fx(2)%fxReverb',
		'UserBass_patch%fx(2)%fxRingMod',
		'UserBass_patch%fx(2)%fxRotary',
		'UserBass_patch%fx(2)%fxSitarSim',
		'UserBass_patch%fx(2)%fxSlicer',
		'UserBass_patch%fx(2)%fxSlowGear',
		'UserBass_patch%fx(2)%fxSlowGearBass',
		'UserBass_patch%fx(2)%fxSoundHold',
		'UserBass_patch%fx(2)%fxTWah',
		'UserBass_patch%fx(2)%fxTWahBass',
		'UserBass_patch%fx(2)%fxTremolo',
		'UserBass_patch%fx(2)%fxVibrato',
		'UserBass_patch%fx(2)%fxWah',
		
		'UserBass_patch%fx(3)%fx',
		'UserBass_patch%fx(3)%fxAcReso',
		'UserBass_patch%fx(3)%fxAWah',
		'UserBass_patch%fx(3)%fxChorus',
		'UserBass_patch%fx(3)%fxCVibe',
		'UserBass_patch%fx(3)%fxComp',
		'UserBass_patch%fx(3)%fxDefretter',
		'UserBass_patch%fx(3)%fxDefretterBass',
		'UserBass_patch%fx(3)%fxDelay',
		'UserBass_patch%fx(3)%fxFlanger',
		'UserBass_patch%fx(3)%fxFlangerBass',
		'UserBass_patch%fx(3)%fxFv',
		'UserBass_patch%fx(3)%fxGEq',
		'UserBass_patch%fx(3)%fxHarmonist',
		'UserBass_patch%fx(3)%fxHumanizer',
		'UserBass_patch%fx(3)%fxIsolator',
		'UserBass_patch%fx(3)%fxLimiter',
		'UserBass_patch%fx(3)%fxLofi',
		'UserBass_patch%fx(3)%fxOctave',
		'UserBass_patch%fx(3)%fxOctaveBass',
		'UserBass_patch%fx(3)%fxPan',
		'UserBass_patch%fx(3)%fxPEq',
		'UserBass_patch%fx(3)%fxPedalBend',
		'UserBass_patch%fx(3)%fxPhaser',
		'UserBass_patch%fx(3)%fxPitchShift',
		'UserBass_patch%fx(3)%fxReverb',
		'UserBass_patch%fx(3)%fxRingMod',
		'UserBass_patch%fx(3)%fxRotary',
		'UserBass_patch%fx(3)%fxSitarSim',
		'UserBass_patch%fx(3)%fxSlicer',
		'UserBass_patch%fx(3)%fxSlowGear',
		'UserBass_patch%fx(3)%fxSlowGearBass',
		'UserBass_patch%fx(3)%fxSoundHold',
		'UserBass_patch%fx(3)%fxTWah',
		'UserBass_patch%fx(3)%fxTWahBass',
		'UserBass_patch%fx(3)%fxTremolo',
		'UserBass_patch%fx(3)%fxVibrato',
		'UserBass_patch%fx(3)%fxWah',
		
		'UserBass_patch%reverb',
	];
	this.temporarySet = {
		'UserBass_patch%common'                 : 'Temp_patchBass%common'                 ,
		// 'UserBass_patch%common(2)'              : 'Temp_patchBass%common(2)'              ,
		'UserBass_patch%led'                    : 'Temp_patchBass%led'                    ,
		'UserBass_patch%assign(1)'              : 'Temp_patchBass%assign(1)'              ,
		'UserBass_patch%assign(2)'              : 'Temp_patchBass%assign(2)'              ,
		'UserBass_patch%assign(3)'              : 'Temp_patchBass%assign(3)'              ,
		'UserBass_patch%assign(4)'              : 'Temp_patchBass%assign(4)'              ,
		'UserBass_patch%assign(5)'              : 'Temp_patchBass%assign(5)'              ,
		'UserBass_patch%assign(6)'              : 'Temp_patchBass%assign(6)'              ,
		'UserBass_patch%assign(7)'              : 'Temp_patchBass%assign(7)'              ,
		'UserBass_patch%assign(8)'              : 'Temp_patchBass%assign(8)'              ,
		'UserBass_patch%assign(9)'              : 'Temp_patchBass%assign(9)'              ,
		'UserBass_patch%assign(10)'             : 'Temp_patchBass%assign(10)'             ,
		'UserBass_patch%assign(11)'             : 'Temp_patchBass%assign(11)'             ,
		'UserBass_patch%assign(12)'             : 'Temp_patchBass%assign(12)'             ,
		'UserBass_patch%assign(13)'             : 'Temp_patchBass%assign(13)'             ,
		'UserBass_patch%assign(14)'             : 'Temp_patchBass%assign(14)'             ,
		'UserBass_patch%assign(15)'             : 'Temp_patchBass%assign(15)'             ,
		'UserBass_patch%assign(16)'             : 'Temp_patchBass%assign(16)'             ,
//		'UserBass_patch%padding'                : 'Temp_patchBass%padding'                ,

		'UserBass_patch%efct'                   : 'Temp_patchBass%efct'                   ,
		'UserBass_patch%gtr2midi'               : 'Temp_patchBass%gtr2midi'               ,

		'UserBass_patch%inst(1)%inst'           : 'Temp_patchBass%inst(1)%inst'           ,
		'UserBass_patch%inst(1)%instDynaSynth'  : 'Temp_patchBass%inst(1)%instDynaSynth'  ,
		'UserBass_patch%inst(1)%instOscSynth'   : 'Temp_patchBass%inst(1)%instOscSynth'   ,
		'UserBass_patch%inst(1)%instAnalogGr'      : 'Temp_patchBass%inst(1)%instAnalogGr'      ,
		// 'UserBass_patch%inst(1)%instGr300'      : 'Temp_patchBass%inst(1)%instGr300'      ,
		'UserBass_patch%inst(1)%instEBass'      : 'Temp_patchBass%inst(1)%instEBass'      ,
		'UserBass_patch%inst(1)%instAcBass'      : 'Temp_patchBass%inst(1)%instAcBass'      ,
		'UserBass_patch%inst(1)%instEGtr'       : 'Temp_patchBass%inst(1)%instEGtr'       ,
		// 'UserBass_patch%inst(1)%instAcoustic'   : 'Temp_patchBass%inst(1)%instAcoustic'   ,
		// 'UserBass_patch%inst(1)%instVioGtr'     : 'Temp_patchBass%inst(1)%instVioGtr'     ,
		'UserBass_patch%inst(1)%instPolyFx'     : 'Temp_patchBass%inst(1)%instPolyFx'     ,
		'UserBass_patch%inst(1)%instAltTune'    : 'Temp_patchBass%inst(1)%instAltTune'    ,

		'UserBass_patch%inst(2)%inst'           : 'Temp_patchBass%inst(2)%inst'           ,
		'UserBass_patch%inst(2)%instDynaSynth'  : 'Temp_patchBass%inst(2)%instDynaSynth'  ,
		'UserBass_patch%inst(2)%instOscSynth'   : 'Temp_patchBass%inst(2)%instOscSynth'   ,
		// 'UserBass_patch%inst(2)%instGr300'      : 'Temp_patchBass%inst(2)%instGr300'      ,
		'UserBass_patch%inst(2)%instAnalogGr'      : 'Temp_patchBass%inst(2)%instAnalogGr'      ,
		'UserBass_patch%inst(2)%instEBass'      : 'Temp_patchBass%inst(2)%instEBass'      ,
		'UserBass_patch%inst(2)%instAcBass'      : 'Temp_patchBass%inst(2)%instAcBass'      ,
		'UserBass_patch%inst(2)%instEGtr'       : 'Temp_patchBass%inst(2)%instEGtr'       ,
		// 'UserBass_patch%inst(2)%instAcoustic'   : 'Temp_patchBass%inst(2)%instAcoustic'   ,
		// 'UserBass_patch%inst(2)%instVioGtr'     : 'Temp_patchBass%inst(2)%instVioGtr'     ,
		'UserBass_patch%inst(2)%instPolyFx'     : 'Temp_patchBass%inst(2)%instPolyFx'     ,
		'UserBass_patch%inst(2)%instAltTune'    : 'Temp_patchBass%inst(2)%instAltTune'    ,

		'UserBass_patch%inst(3)%inst'           : 'Temp_patchBass%inst(3)%inst'           ,
		'UserBass_patch%inst(3)%instDynaSynth'  : 'Temp_patchBass%inst(3)%instDynaSynth'  ,
		'UserBass_patch%inst(3)%instOscSynth'   : 'Temp_patchBass%inst(3)%instOscSynth'   ,
		'UserBass_patch%inst(3)%instAnalogGr'      : 'Temp_patchBass%inst(3)%instAnalogGr'      ,
		// 'UserBass_patch%inst(3)%instGr300'      : 'Temp_patchBass%inst(3)%instGr300'      ,
		'UserBass_patch%inst(3)%instEBass'      : 'Temp_patchBass%inst(3)%instEBass'      ,
		'UserBass_patch%inst(3)%instAcBass'      : 'Temp_patchBass%inst(3)%instAcBass'      ,
		'UserBass_patch%inst(3)%instEGtr'       : 'Temp_patchBass%inst(3)%instEGtr'       ,
		// 'UserBass_patch%inst(3)%instAcoustic'   : 'Temp_patchBass%inst(3)%instAcoustic'   ,
		// 'UserBass_patch%inst(3)%instVioGtr'     : 'Temp_patchBass%inst(3)%instVioGtr'     ,
		'UserBass_patch%inst(3)%instPolyFx'     : 'Temp_patchBass%inst(3)%instPolyFx'     ,
		'UserBass_patch%inst(3)%instAltTune'    : 'Temp_patchBass%inst(3)%instAltTune'    ,

		'UserBass_patch%comp'                   : 'Temp_patchBass%comp'                   ,
		'UserBass_patch%dist'                   : 'Temp_patchBass%dist'                   ,
		'UserBass_patch%amp'                    : 'Temp_patchBass%amp'                    ,
		'UserBass_patch%ns'                     : 'Temp_patchBass%ns'                     ,
		'UserBass_patch%eq(1)'                  : 'Temp_patchBass%eq(1)'                  ,
		'UserBass_patch%eq(2)'                  : 'Temp_patchBass%eq(2)'                  ,
		'UserBass_patch%delay(1)'               : 'Temp_patchBass%delay(1)'               ,
		'UserBass_patch%delay(2)'               : 'Temp_patchBass%delay(2)'               ,
		'UserBass_patch%mstDelay'               : 'Temp_patchBass%mstDelay'               ,
		'UserBass_patch%chorus'                 : 'Temp_patchBass%chorus'                 ,

		'UserBass_patch%fx(1)%fx'               : 'Temp_patchBass%fx(1)%fx'               ,
		'UserBass_patch%fx(1)%fxAcReso'         : 'Temp_patchBass%fx(1)%fxAcReso'         ,
		'UserBass_patch%fx(1)%fxAWah'           : 'Temp_patchBass%fx(1)%fxAWah'           ,
		'UserBass_patch%fx(1)%fxChorus'         : 'Temp_patchBass%fx(1)%fxChorus'         ,
		'UserBass_patch%fx(1)%fxCVibe'          : 'Temp_patchBass%fx(1)%fxCVibe'          ,
		'UserBass_patch%fx(1)%fxComp'           : 'Temp_patchBass%fx(1)%fxComp'           ,
		'UserBass_patch%fx(1)%fxDefretter'      : 'Temp_patchBass%fx(1)%fxDefretter'      ,
		'UserBass_patch%fx(1)%fxDefretterBass'  : 'Temp_patchBass%fx(1)%fxDefretterBass'  ,
		'UserBass_patch%fx(1)%fxDelay'          : 'Temp_patchBass%fx(1)%fxDelay'          ,
		'UserBass_patch%fx(1)%fxFlanger'        : 'Temp_patchBass%fx(1)%fxFlanger'        ,
		'UserBass_patch%fx(1)%fxFlangerBass'    : 'Temp_patchBass%fx(1)%fxFlangerBass'    ,
		'UserBass_patch%fx(1)%fxFv'             : 'Temp_patchBass%fx(1)%fxFv'             ,
		'UserBass_patch%fx(1)%fxGEq'            : 'Temp_patchBass%fx(1)%fxGEq'            ,
		'UserBass_patch%fx(1)%fxHarmonist'      : 'Temp_patchBass%fx(1)%fxHarmonist'      ,
		'UserBass_patch%fx(1)%fxHumanizer'      : 'Temp_patchBass%fx(1)%fxHumanizer'      ,
		'UserBass_patch%fx(1)%fxIsolator'       : 'Temp_patchBass%fx(1)%fxIsolator'       ,
		'UserBass_patch%fx(1)%fxLimiter'        : 'Temp_patchBass%fx(1)%fxLimiter'        ,
		'UserBass_patch%fx(1)%fxLofi'           : 'Temp_patchBass%fx(1)%fxLofi'           ,
		'UserBass_patch%fx(1)%fxOctave'         : 'Temp_patchBass%fx(1)%fxOctave'         ,
		'UserBass_patch%fx(1)%fxOctaveBass'     : 'Temp_patchBass%fx(1)%fxOctaveBass'     ,
		'UserBass_patch%fx(1)%fxPan'            : 'Temp_patchBass%fx(1)%fxPan'            ,
		'UserBass_patch%fx(1)%fxPEq'            : 'Temp_patchBass%fx(1)%fxPEq'            ,
		'UserBass_patch%fx(1)%fxPedalBend'      : 'Temp_patchBass%fx(1)%fxPedalBend'      ,
		'UserBass_patch%fx(1)%fxPhaser'         : 'Temp_patchBass%fx(1)%fxPhaser'         ,
		'UserBass_patch%fx(1)%fxPitchShift'     : 'Temp_patchBass%fx(1)%fxPitchShift'     ,
		'UserBass_patch%fx(1)%fxReverb'         : 'Temp_patchBass%fx(1)%fxReverb'         ,
		'UserBass_patch%fx(1)%fxRingMod'        : 'Temp_patchBass%fx(1)%fxRingMod'        ,
		'UserBass_patch%fx(1)%fxRotary'         : 'Temp_patchBass%fx(1)%fxRotary'         ,
		'UserBass_patch%fx(1)%fxSitarSim'       : 'Temp_patchBass%fx(1)%fxSitarSim'       ,
		'UserBass_patch%fx(1)%fxSlicer'         : 'Temp_patchBass%fx(1)%fxSlicer'         ,
		'UserBass_patch%fx(1)%fxSlowGear'       : 'Temp_patchBass%fx(1)%fxSlowGear'       ,
		'UserBass_patch%fx(1)%fxSlowGearBass'   : 'Temp_patchBass%fx(1)%fxSlowGearBass'   ,
		'UserBass_patch%fx(1)%fxSoundHold'      : 'Temp_patchBass%fx(1)%fxSoundHold'      ,
		'UserBass_patch%fx(1)%fxTWah'           : 'Temp_patchBass%fx(1)%fxTWah'           ,
		'UserBass_patch%fx(1)%fxTWahBass'       : 'Temp_patchBass%fx(1)%fxTWahBass'       ,
		'UserBass_patch%fx(1)%fxTremolo'        : 'Temp_patchBass%fx(1)%fxTremolo'        ,
		'UserBass_patch%fx(1)%fxVibrato'        : 'Temp_patchBass%fx(1)%fxVibrato'        ,
		'UserBass_patch%fx(1)%fxWah'            : 'Temp_patchBass%fx(1)%fxWah'            ,
		
		'UserBass_patch%fx(2)%fx'               : 'Temp_patchBass%fx(2)%fx'               ,
		'UserBass_patch%fx(2)%fxAcReso'         : 'Temp_patchBass%fx(2)%fxAcReso'         ,
		'UserBass_patch%fx(2)%fxAWah'           : 'Temp_patchBass%fx(2)%fxAWah'           ,
		'UserBass_patch%fx(2)%fxChorus'         : 'Temp_patchBass%fx(2)%fxChorus'         ,
		'UserBass_patch%fx(2)%fxCVibe'          : 'Temp_patchBass%fx(2)%fxCVibe'          ,
		'UserBass_patch%fx(2)%fxComp'           : 'Temp_patchBass%fx(2)%fxComp'           ,
		'UserBass_patch%fx(2)%fxDefretter'      : 'Temp_patchBass%fx(2)%fxDefretter'      ,
		'UserBass_patch%fx(2)%fxDefretterBass'  : 'Temp_patchBass%fx(2)%fxDefretterBass'  ,
		'UserBass_patch%fx(2)%fxDelay'          : 'Temp_patchBass%fx(2)%fxDelay'          ,
		'UserBass_patch%fx(2)%fxFlanger'        : 'Temp_patchBass%fx(2)%fxFlanger'        ,
		'UserBass_patch%fx(2)%fxFlangerBass'    : 'Temp_patchBass%fx(2)%fxFlangerBass'    ,
		'UserBass_patch%fx(2)%fxFv'             : 'Temp_patchBass%fx(2)%fxFv'             ,
		'UserBass_patch%fx(2)%fxGEq'            : 'Temp_patchBass%fx(2)%fxGEq'            ,
		'UserBass_patch%fx(2)%fxHarmonist'      : 'Temp_patchBass%fx(2)%fxHarmonist'      ,
		'UserBass_patch%fx(2)%fxHumanizer'      : 'Temp_patchBass%fx(2)%fxHumanizer'      ,
		'UserBass_patch%fx(2)%fxIsolator'       : 'Temp_patchBass%fx(2)%fxIsolator'       ,
		'UserBass_patch%fx(2)%fxLimiter'        : 'Temp_patchBass%fx(2)%fxLimiter'        ,
		'UserBass_patch%fx(2)%fxLofi'           : 'Temp_patchBass%fx(2)%fxLofi'           ,
		'UserBass_patch%fx(2)%fxOctave'         : 'Temp_patchBass%fx(2)%fxOctave'         ,
		'UserBass_patch%fx(2)%fxOctaveBass'     : 'Temp_patchBass%fx(2)%fxOctaveBass'     ,
		'UserBass_patch%fx(2)%fxPan'            : 'Temp_patchBass%fx(2)%fxPan'            ,
		'UserBass_patch%fx(2)%fxPEq'            : 'Temp_patchBass%fx(2)%fxPEq'            ,
		'UserBass_patch%fx(2)%fxPedalBend'      : 'Temp_patchBass%fx(2)%fxPedalBend'      ,
		'UserBass_patch%fx(2)%fxPhaser'         : 'Temp_patchBass%fx(2)%fxPhaser'         ,
		'UserBass_patch%fx(2)%fxPitchShift'     : 'Temp_patchBass%fx(2)%fxPitchShift'     ,
		'UserBass_patch%fx(2)%fxReverb'         : 'Temp_patchBass%fx(2)%fxReverb'         ,
		'UserBass_patch%fx(2)%fxRingMod'        : 'Temp_patchBass%fx(2)%fxRingMod'        ,
		'UserBass_patch%fx(2)%fxRotary'         : 'Temp_patchBass%fx(2)%fxRotary'         ,
		'UserBass_patch%fx(2)%fxSitarSim'       : 'Temp_patchBass%fx(2)%fxSitarSim'       ,
		'UserBass_patch%fx(2)%fxSlicer'         : 'Temp_patchBass%fx(2)%fxSlicer'         ,
		'UserBass_patch%fx(2)%fxSlowGear'       : 'Temp_patchBass%fx(2)%fxSlowGear'       ,
		'UserBass_patch%fx(2)%fxSlowGearBass'   : 'Temp_patchBass%fx(2)%fxSlowGearBass'   ,
		'UserBass_patch%fx(2)%fxSoundHold'      : 'Temp_patchBass%fx(2)%fxSoundHold'      ,
		'UserBass_patch%fx(2)%fxTWah'           : 'Temp_patchBass%fx(2)%fxTWah'           ,
		'UserBass_patch%fx(2)%fxTWahBass'       : 'Temp_patchBass%fx(2)%fxTWahBass'       ,
		'UserBass_patch%fx(2)%fxTremolo'        : 'Temp_patchBass%fx(2)%fxTremolo'        ,
		'UserBass_patch%fx(2)%fxVibrato'        : 'Temp_patchBass%fx(2)%fxVibrato'        ,
		'UserBass_patch%fx(2)%fxWah'            : 'Temp_patchBass%fx(2)%fxWah'            ,
		
		'UserBass_patch%fx(3)%fx'               : 'Temp_patchBass%fx(3)%fx'               ,
		'UserBass_patch%fx(3)%fxAcReso'         : 'Temp_patchBass%fx(3)%fxAcReso'         ,
		'UserBass_patch%fx(3)%fxAWah'           : 'Temp_patchBass%fx(3)%fxAWah'           ,
		'UserBass_patch%fx(3)%fxChorus'         : 'Temp_patchBass%fx(3)%fxChorus'         ,
		'UserBass_patch%fx(3)%fxCVibe'          : 'Temp_patchBass%fx(3)%fxCVibe'          ,
		'UserBass_patch%fx(3)%fxComp'           : 'Temp_patchBass%fx(3)%fxComp'           ,
		'UserBass_patch%fx(3)%fxDefretter'      : 'Temp_patchBass%fx(3)%fxDefretter'      ,
		'UserBass_patch%fx(3)%fxDefretterBass'  : 'Temp_patchBass%fx(3)%fxDefretterBass'  ,
		'UserBass_patch%fx(3)%fxDelay'          : 'Temp_patchBass%fx(3)%fxDelay'          ,
		'UserBass_patch%fx(3)%fxFlanger'        : 'Temp_patchBass%fx(3)%fxFlanger'        ,
		'UserBass_patch%fx(3)%fxFlangerBass'    : 'Temp_patchBass%fx(3)%fxFlangerBass'    ,
		'UserBass_patch%fx(3)%fxFv'             : 'Temp_patchBass%fx(3)%fxFv'             ,
		'UserBass_patch%fx(3)%fxGEq'            : 'Temp_patchBass%fx(3)%fxGEq'            ,
		'UserBass_patch%fx(3)%fxHarmonist'      : 'Temp_patchBass%fx(3)%fxHarmonist'      ,
		'UserBass_patch%fx(3)%fxHumanizer'      : 'Temp_patchBass%fx(3)%fxHumanizer'      ,
		'UserBass_patch%fx(3)%fxIsolator'       : 'Temp_patchBass%fx(3)%fxIsolator'       ,
		'UserBass_patch%fx(3)%fxLimiter'        : 'Temp_patchBass%fx(3)%fxLimiter'        ,
		'UserBass_patch%fx(3)%fxLofi'           : 'Temp_patchBass%fx(3)%fxLofi'           ,
		'UserBass_patch%fx(3)%fxOctave'         : 'Temp_patchBass%fx(3)%fxOctave'         ,
		'UserBass_patch%fx(3)%fxOctaveBass'     : 'Temp_patchBass%fx(3)%fxOctaveBass'     ,
		'UserBass_patch%fx(3)%fxPan'            : 'Temp_patchBass%fx(3)%fxPan'            ,
		'UserBass_patch%fx(3)%fxPEq'            : 'Temp_patchBass%fx(3)%fxPEq'            ,
		'UserBass_patch%fx(3)%fxPedalBend'      : 'Temp_patchBass%fx(3)%fxPedalBend'      ,
		'UserBass_patch%fx(3)%fxPhaser'         : 'Temp_patchBass%fx(3)%fxPhaser'         ,
		'UserBass_patch%fx(3)%fxPitchShift'     : 'Temp_patchBass%fx(3)%fxPitchShift'     ,
		'UserBass_patch%fx(3)%fxReverb'         : 'Temp_patchBass%fx(3)%fxReverb'         ,
		'UserBass_patch%fx(3)%fxRingMod'        : 'Temp_patchBass%fx(3)%fxRingMod'        ,
		'UserBass_patch%fx(3)%fxRotary'         : 'Temp_patchBass%fx(3)%fxRotary'         ,
		'UserBass_patch%fx(3)%fxSitarSim'       : 'Temp_patchBass%fx(3)%fxSitarSim'       ,
		'UserBass_patch%fx(3)%fxSlicer'         : 'Temp_patchBass%fx(3)%fxSlicer'         ,
		'UserBass_patch%fx(3)%fxSlowGear'       : 'Temp_patchBass%fx(3)%fxSlowGear'       ,
		'UserBass_patch%fx(3)%fxSlowGearBass'   : 'Temp_patchBass%fx(3)%fxSlowGearBass'   ,
		'UserBass_patch%fx(3)%fxSoundHold'      : 'Temp_patchBass%fx(3)%fxSoundHold'      ,
		'UserBass_patch%fx(3)%fxTWah'           : 'Temp_patchBass%fx(3)%fxTWah'           ,
		'UserBass_patch%fx(3)%fxTWahBass'       : 'Temp_patchBass%fx(3)%fxTWahBass'       ,
		'UserBass_patch%fx(3)%fxTremolo'        : 'Temp_patchBass%fx(3)%fxTremolo'        ,
		'UserBass_patch%fx(3)%fxVibrato'        : 'Temp_patchBass%fx(3)%fxVibrato'        ,
		'UserBass_patch%fx(3)%fxWah'            : 'Temp_patchBass%fx(3)%fxWah'            ,
		
		'UserBass_patch%reverb'                 : 'Temp_patchBass%reverb'                 ,
	};

	this.columnInfo = [
		{ type: 'text16', width: '16' },
	];
	this.value = function (paramSet, column) {
		var text = '';
		var data = paramSet['UserBass_patch%common'];
		for (var i = 0; i < 16; i++) {
			text += String.fromCharCode(parseInt(data[i], 16));
		}
		return text;
	}
	this.setValue = function (paramSet, column, value) {
		var data = paramSet['UserBass_patch%common'];
		for (var i = 0; i < 16; i++) {
			var code = (i < value.length) ? value.charCodeAt(i) : 32;
			if (code < 32 || code > 127) code = 32;
			data[i] = code.toString(16);
		}
	}

	this.readStart = function (midi) { }
	this.readStop = function (midi) { }
	this.writeStart = function (midi) { }
	this.writeCommand = function (midi) { }
	this.writeStop = function (midi) { }
	this.writeTemporaryStart = function (midi, row) { }
	this.writeTemporaryStop = function (midi) { }
	this.previewStart = function (midi) { }
	this.previewStop = function (midi) { }
	this.getPatchVariationSet = function() { return this.exclusionSet; }
}

